AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'test/**/*'
    - 'bin/**/*'
# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: 80
  Exclude:
    - "**/*_spec.rb"
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/ClassLength:
  Enabled: false
Naming:
  Style/AccessorMethodName:
    Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
